export const externalAssistantMcpContract = Object.freeze({
  transport: "stdio" as const,
  capabilityNames: Object.freeze([
    "candidature.create",
    "application_information.task.read",
    "application_information.proposals.submit",
    "interview_preparation.context.read",
    "interview_preparation.result.save",
    "application.document_target.read",
    "reusable_cv.list",
    "reusable_cv.read",
    "application_cv.create",
    "cv_field.context.read",
    "cv_field.write",
    "application_cover_letter.create",
    "cover_letter.write",
    "document_rendering.status",
    "document.render",
    "installer.status.read",
    "installer.rendering.self_test",
    "configurator.status.read",
    "configurator.ai_connection.save",
    "configurator.ai_operation.validate",
    "configurator.ai_operation.default",
  ] as const),
  toolNames: Object.freeze([
    "candidature_create",
    "application_information_task_read",
    "application_information_proposals_submit",
    "interview_preparation_context_read",
    "interview_preparation_result_save",
    "application_document_target_read",
    "reusable_cvs_list",
    "reusable_cv_read",
    "application_cv_create",
    "cv_field_context_read",
    "cv_field_write",
    "application_cover_letter_create",
    "cover_letter_write",
    "document_rendering_status",
    "document_render",
    "installer_status_read",
    "installer_rendering_self_test",
    "configurator_status_read",
    "configurator_ai_connection_save",
    "configurator_ai_operation_validate",
    "configurator_ai_operation_default",
  ] as const),
  permissionScope:
    "Perform only typed AAAAT product intentions: create an application from supplied Source material; work with the one locally selected application's prepared application-information or interview-preparation task; separately work with the one application the user explicitly selected for external document work; choose and inspect one reusable CV; create and write an application CV one existing field at a time; create and write one application cover letter; inspect rendering availability; render only a session-bound document; inspect setup readiness; and, only while the user enables the matching local setup authority, run AAAAT's fixed rendering self-test or save/validate/select typed AI connection configuration. Application-information/interview selection does not grant document authority. No capability provides generic candidature/document CRUD, corpus access, storage access, Blueprint control, or machine authority." as const,
  privacyDisclosure:
    "The external assistant receives only the payload of the bounded capability it invokes. Application-information uses one locally selected application, task-local field/choice references, retained task context, and only the field information AAAAT assigned and allows for AI use. Existing-application document work uses a separate deliberate local selection. Reusable-CV choice exposes only user-facing names; only the chosen reusable CV may then expose permitted content. Content without an applicable AI-disclosure choice fails closed: actual values and semantic item data stay local and only AAAAT-supplied USERPRIVATE placeholders leave. Exact placeholder/value bindings remain local, are scoped to document work, and only exact unambiguous placeholders AAAAT supplied are restored before editable CV or cover-letter content is saved. Document references are session-local and expose no durable document/application IDs. Rendering returns only availability or success/failure and no paths, TeX, PDF content, Blueprint choices, commands, process access, or filesystem authority. No application capability exposes corpus browsing, generic database/filesystem/process/shell authority, or unrelated application data. Setup tools remain independently bounded and expose no application data." as const,
});
